export type Skill = {
  id: number;
  name: string;
  skill: number;
  icon: string;
  type: number;
  parent?: number;
  favorite?: boolean;
};

export const skills: Skill[] = [
  { id: 1, name: "HTML5", skill: 100, icon: "html5.png", type: 2 },
  { id: 2, name: "CSS3", skill: 100, icon: "css-3.png", type: 2 },
  { id: 3, name: "PHP", skill: 100, icon: "php.png", type: 2 },
  { id: 4, name: "SQL", skill: 100, icon: "sql.png", type: 2 },
  { id: 5, name: "Javascript", skill: 100, icon: "js.png", type: 2 },
  { id: 6, name: "C#", skill: 80, icon: "csharp.png", type: 2 },
  { id: 7, name: "VB.Net", skill: 70, icon: "vbnet.png", type: 2 },
  { id: 8, name: "Java", skill: 60, icon: "java.png", type: 2 },
  { id: 9, name: "Swift", skill: 10, icon: "swift.png", type: 2 },
  { id: 10, name: "C", skill: 50, icon: "c.png", type: 2 },
  { id: 11, name: "C++", skill: 50, icon: "cpp.png", type: 2 },
  { id: 12, name: "Python", skill: 30, icon: "python.png", type: 2 },
  { id: 13, name: "BluePrints", skill: 100, icon: "blueprint.png", type: 2 },
  { id: 14, name: "Bash", skill: 80, icon: "bash.png", type: 2 },
  { id: 15, name: "Batch", skill: 70, icon: "batch.png", type: 2 },
  { id: 16, name: "Powershell", skill: 60, icon: "powershell.png", type: 2 },
  { id: 17, name: "Yaml", skill: 60, icon: "yaml.png", type: 2 },
  {
    id: 18,
    name: "Angular.js",
    skill: 70,
    icon: "angularjs.png",
    parent: 5,
    type: 3,
  },
  {
    id: 19,
    name: "JQuery",
    skill: 100,
    icon: "jquery.png",
    parent: 5,
    type: 3,
  },
  {
    id: 20,
    name: "Bootstrap",
    skill: 100,
    icon: "bootstrap.png",
    parent: 2,
    type: 3,
  },
  { id: 21, name: "SQLite", skill: 80, icon: "sqlite.png", parent: 4, type: 3 },
  { id: 22, name: "React", skill: 10, icon: "reactjs.png", parent: 5, type: 3 },
  {
    id: 23,
    name: "MongoDB",
    skill: 20,
    icon: "mongodb.png",
    parent: 4,
    type: 3,
  },
  {
    id: 24,
    name: "Xamarin",
    skill: 20,
    icon: "xamarin.png",
    parent: 6,
    type: 3,
  },
  {
    id: 25,
    name: "SQL Server",
    skill: 70,
    icon: "sqlserver.png",
    parent: 4,
    type: 3,
  },
  {
    id: 26,
    name: "WinForms",
    skill: 60,
    icon: "winforms.png",
    parent: 6,
    type: 3,
  },
  {
    id: 27,
    name: "Vanilla.JS",
    skill: 95,
    icon: "vanillajs.png",
    parent: 5,
    type: 3,
  },
  {
    id: 28,
    name: "MySQL",
    skill: 80,
    icon: "mysql.png",
    parent: 4,
    type: 3,
    favorite: true,
  },
  { id: 29, name: "WPF", skill: 70, icon: "xaml.png", parent: 6, type: 3 },
  {
    id: 30,
    name: "Android",
    skill: 20,
    icon: "android.png",
    parent: 8,
    type: 3,
  },
  {
    id: 31,
    name: "Node.JS",
    skill: 85,
    icon: "nodejs.png",
    parent: 5,
    type: 3,
    favorite: true,
  },
  {
    id: 32,
    name: "Electron",
    skill: 70,
    icon: "electron.png",
    parent: 5,
    type: 3,
    favorite: true,
  },
  {
    id: 33,
    name: "Unreal Engine",
    skill: 90,
    icon: "ue.png",
    parent: 13,
    type: 3,
    favorite: true,
  },
  { id: 34, name: "VueJS", skill: 70, icon: "vuejs.png", parent: 5, type: 3 },
  {
    id: 35,
    name: "Knockoutjs",
    skill: 50,
    icon: "knockoutjs.png",
    parent: 5,
    type: 3,
  },
  {
    id: 36,
    name: "Materialize",
    skill: 100,
    icon: "materialize.png",
    parent: 2,
    type: 3,
  },
  {
    id: 37,
    name: "Angular",
    skill: 20,
    icon: "angular.png",
    parent: 5,
    type: 3,
  },
  {
    id: 38,
    name: "Svelte",
    skill: 75,
    icon: "svelte.png",
    parent: 5,
    type: 3,
    favorite: true,
  },
  { id: 39, name: "Nx", skill: 50, icon: "nx.png", parent: 5, type: 3 },
  { id: 40, name: "Lerna", skill: 50, icon: "lerna.png", parent: 5, type: 3 },
  { id: 41, name: "Apache", skill: 90, icon: "apache.png", type: 4 },
  { id: 42, name: "Photoshop", skill: 70, icon: "photoshop.png", type: 4 },
  {
    id: 43,
    name: "Docker",
    skill: 70,
    icon: "docker.png",
    type: 4,
    favorite: true,
  },
  { id: 44, name: "TeamCity", skill: 60, icon: "teamcity.png", type: 4 },
  { id: 45, name: "YouTrack", skill: 60, icon: "youtrack.png", type: 4 },
  { id: 46, name: "Gitlab", skill: 80, icon: "gitlab.png", type: 4 },
  { id: 47, name: "Bitbucket", skill: 80, icon: "bitbucket.png", type: 4 },
  { id: 48, name: "Jira", skill: 70, icon: "jira.png", type: 4 },
  { id: 49, name: "Git", skill: 90, icon: "git.png", type: 4, favorite: true },
  {
    id: 50,
    name: "Azure DevOps",
    skill: 70,
    icon: "azuredevops.png",
    type: 4,
    favorite: true,
  },
  { id: 51, name: "Teams", skill: 100, icon: "teams.png", type: 4 },
  { id: 52, name: "Slack", skill: 100, icon: "slack.png", type: 4 },
  { id: 53, name: "Discord", skill: 100, icon: "discord.png", type: 4 },
  { id: 54, name: "AWS", skill: 20, icon: "aws.png", type: 4 },
  { id: 55, name: "Azure", skill: 20, icon: "azure.png", type: 4 },
  { id: 58, name: "Testing", skill: 60, icon: "testing.png", type: 1 },
  { id: 59, name: "Linux", skill: 60, icon: "linux.png", type: 1 },
  { id: 60, name: "Mobile", skill: 30, icon: "mobile.png", type: 1 },
  { id: 61, name: "ERP", skill: 60, icon: "erp.png", type: 1 },
  { id: 62, name: "iOs", skill: 10, icon: "ios.png", type: 1 },
  { id: 63, name: "Scrum", skill: 70, icon: "agile.png", type: 1 },
  {
    id: 64,
    name: "Agile",
    skill: 60,
    icon: "agile.png",
    type: 1,
    favorite: true,
  },
  {
    id: 65,
    name: "CI/CD",
    skill: 80,
    icon: "rocket.png",
    type: 1,
    favorite: true,
  },
  { id: 66, name: "DevOps", skill: 60, icon: "devops.png", type: 1 },
  { id: 67, name: "PM2", skill: 75, icon: "pm2.png", type: 4, favorite: true },
  {
    id: 68,
    name: "Event Sourcing",
    skill: 45,
    icon: "eventsourcing.png",
    type: 4,
  },
  { id: 69, name: "RabbitMQ", skill: 45, icon: "rabbitmq.png", type: 4 },
  { id: 70, name: "Kafka", skill: 25, icon: "kafka.png", type: 4 },
  { id: 71, name: "Go", skill: 25, icon: "go.png", type: 2 },
  {
    id: 72,
    name: "Svelte Native",
    skill: 45,
    icon: "sveltenative.png",
    parent: 38,
    type: 3,
  },
];
